/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}", //Include all React files in the src folder
  ],
  theme: {
    extend: {
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
      },
      colors: {
        primary: "#EDA415",
        textColor: "#1B5A7D",
        secoundTextColor: "#003F62",
        thirdTextColor: "#232323",
        forthTextColor: "#434343",
        fifthTextColor: "#4A4A4A",
        sixthTextColor: "#C33131",
        seventhTextColor: "#2E8FC5",
        eightTextColor: "#292D32",
        nineTextColor: "#3B3B3B",
        tenTextColor: "#316887",
        elevenTextColor: "#606060",
        twelveTextColor: "#30BD57",
        thirteenTextColor: "#4F4F4F",
        forteenTextColor: "#272727",
        fifteenTextColor: "#5D5D5D",
        sixteenTextColor: "#797979",
        seventeenTextColor: "#265f7f",
        eighteenTextColor: "#373737",

        borderColor: "#ADADAD",
        secoundBorderColor: "#BDBDBD",
        thirdBorderColor: "#B6B6B6",
        forthBorderColor: "#BABABA",
        fifthBorderColor: "#F2F2F2",
        sicthBorderColor: "#AFAFAF",
        seventhTextColor: "#222222",
        eightBorderColor: "#A9A9A9",
        nineBorderColor: "#DFDFDF",
        tenBorderColor: "#9D9D9D",
        elevenBorderColor: "#B8B8B8",
        twelveBorderColor: "#8F8F8F",

        cartProductCardTextColor: "#2F2F2F",
        navbarLinkTextColor: "#3A3A3A",
        latestNewsBorderColor: "#C8C8C8",
        footerSectionTextColor: "#D9D9D9",
        ProductDetailsBgColor: "#EEEEEE",
        allCategroriesTextColor: "#595959",

        backgroungColor: "#E2F4FF",
        secondBackgroundColor: "#87BCD9",
        thirdBackgroundColor: "#F4F4F4",
        forthBackgroundColor: "#B3D4E5",
        fifthBackgroundColor: "#BC2944",
        sixthBackgroundColor: "#ACACAC",
        seventhBackgrounfColor: "#D0ec48",
        eightBackgrounfColor: "#E42424",
        nineBackgrounfColor: "#1D5F23",
        tenBackgrounfColor: "#2E56A3",
        elevenBackgrounfColor: "#8131A7",
        twelveBackgrounfColor: "#9BC14C",
        hoverBackgroundColor: "#A7D8F3",
      },
      screens: {
        xs: "380px",
        sm: "500px",
        md: "768px",
        lg: "1024px",
        xl: "1130px",
      },
    },
  },
  plugins: [],
};
